### ISSUE TITLE
pointer arithmetic - wrong value

### ISSUE THREAD

**Issue by jens-ox** [jens-ox/OS#4]
Shouldn't e be dereference(p+2) = d = 7?
![os-fehler-folie-2](https://cloud.githubusercontent.com/assets/5368029/19437957/ee0af11c-9477-11e6-9e90-2fabdac3c373.png)

**Comment by mdvjd** [comment]
No it's correct. When you add 2 on pointer p  (Address 40 + 8 Bytes) you get the address 48 obviously. And the value of address 48 is 6.
